#include "AST.h"

#include <iostream>
#include <memory>
#include <string>
#include <sstream>


// Generated by Bison.
//extern int yydebug; // deep parser debuging

int yyparse();

// Generated by Flex.
extern FILE* yyin;

// The AST produced by parser.y.
extern std::unique_ptr<Compiler::Program> parsedProgram;


// ============================================================
// Main
// ============================================================

int main() // LLVM ORC REPL
{
    //yydebug = 1;

    std::cout
        << "========================================\n"
        << "LLVM Compiler REPL\n"
        << "========================================\n"
        << "Type an expression and press Enter.\n"
        << "Type 'e' to quit.\n\n";


    std::string line;


    while (true)
    {
        std::cout << "> ";

        if (!std::getline(std::cin, line))
            break;


        if (line == "e")
            break;


        if (line.empty())
            continue;


        /*
         * Flex normally reads from stdin.
         *
         * For the REPL we create a temporary stream
         * containing exactly one line of source code.
         */
        std::string input = line + "\n";

        FILE* inputFile = tmpfile();

        if (!inputFile)
        {
            std::cerr
                << "Error: could not create input buffer.\n";

            continue;
        }


        fwrite(
            input.c_str(),
            1,
            input.size(),
            inputFile
        );

        rewind(inputFile);


        yyin = inputFile;

        parsedProgram.reset();


        int result = yyparse();


        fclose(inputFile);


        if (result != 0)
        {
            std::cerr
                << "Compilation failed.\n";

            continue;
        }


        if (parsedProgram)
        {
            std::cout
                << "\n=== AST ===\n";

            parsedProgram->print();

            // then we need to take the ast and do the IR code generation
            // and then compile to machine code and run it.

            std::cout
                << "============\n\n";
        }
    }


    std::cout
        << "\nGoodbye!\n";

    return 0;
}
